theme: jekyll-theme-cayman
title: Housing Prices in University Towns
title: Data Acquisition and Cleaning
description: Based on the assignments from Introduction to Data Science in Python by University of Michigan on Coursera
